### ISSUE TITLE
App not opening , Says Please Allow all Permissions

### ISSUE THREAD

**Issue by Hari-Pi** [HiddenPirates/Call-Recorder#1]
The app won't open and i think the issue is call log's permission which even if i select as allow would revert back to don't allow

here's the log

time: 1658158937649
msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS }
stacktrace: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=4528, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.hiddenpirates.callrecorder/com.hiddenpirates.callrecorder.activities.MainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS }
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5368)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7871)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2121)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1766)
	at android.app.Activity.startActivityForResult(Activity.java:5410)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:5368)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivity(Activity.java:5754)
	at android.app.Activity.startActivity(Activity.java:5707)
	at com.hiddenpirates.callrecorder.activities.MainActivity.onRequestPermissionsResult(Unknown Source:67)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8535)
	at android.app.Activity.dispatchActivityResult(Activity.java:8392)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
	... 13 more

**Comment by HiddenPirates** [comment]
Thanks for your feedback. I will investigate this issue. I hope this issue will be solved in the next version.

Suggestion: You can manually allow permission from the app settings page.

**Comment by HiddenPirates** [comment]
Now I hope the problem has been solved.

**Comment by Hari-Pi** [comment]
> Thanks for your feedback. I will investigate this issue. I hope this issue will be solved in the next version.
> 
> Suggestion: You can manually allow permission from the app settings page.

I tried that but it reverts back to Not allow and I don't know why , i even tried granting read_call_log permission from adb but that also didn't worked

**Comment by HiddenPirates** [comment]
Maybe it's your device problem.

**Comment by Hari-Pi** [comment]
So what's the proper way to install the app as a system app? I modified the Axet's call recorder Magisk module and changed the axet's call recorder with your one , so is there any other way of making the apk a system app?

**Comment by HiddenPirates** [comment]
I don't know if there is any other method to sustemize an app. But I use Magisk's systemizer module to systemize an app. You can download this module from this link https://drive.google.com/file/d/10NFjGymmWG5fLpqF2Vhpepyklra2Sfje/view?usp=drivesdk

You can watch this video tutorial https://youtu.be/nV68MHVN9dc


Remember after systemize the app, it will not open because of systemizer module bug. To solve this, reinstall the app again normally.

**Comment by Hari-Pi** [comment]
> I don't know if there is any other method to sustemize an app. But I use Magisk's systemizer module to systemize an app. You can download this module from this link https://drive.google.com/file/d/10NFjGymmWG5fLpqF2Vhpepyklra2Sfje/view?usp=drivesdk
> 
> You can watch this video tutorial https://youtu.be/nV68MHVN9dc
> 
> Remember after systemize the app, it will not open because of systemizer module bug. To solve this, reinstall the app again normally.

Damn that last part of reinstalling the app was something i didn't tried , maybe you should put it out in the Installation instructions
Btw are you going to create a Magisk module for installation because that seems easier to do 
Instead of going through systemise and systemising the app and then Reinstalling it , all you'd need is the permissions XML file and the apk itself of the app
Btw I'll try with systemise again and let you know if it works or not.

**Comment by Hari-Pi** [comment]
> I don't know if there is any other method to sustemize an app. But I use Magisk's systemizer module to systemize an app. You can download this module from this link https://drive.google.com/file/d/10NFjGymmWG5fLpqF2Vhpepyklra2Sfje/view?usp=drivesdk
> 
> You can watch this video tutorial https://youtu.be/nV68MHVN9dc
> 
> Remember after systemize the app, it will not open because of systemizer module bug. To solve this, reinstall the app again normally.

I installed the latest apk and used systemise to turn it into a system app and reinstalled it as you mentioned and it works
Thanks alot for making this application

**Comment by Hari-Pi** [comment]
Hey bro i created this Magisk flashable zip for your Call-Recorder so that we can skip the whole systemise and then reinstall apk step , Also thanks for this amazing app

https://drive.google.com/file/d/1vlIRuKXlLyO-kTI_FaTKKlleC1-yIVLE/view?usp=drivesdk

**Comment by HiddenPirates** [comment]
Thanks bro for your help. Ok I am reopening this issue that users can find it and learn.

**Comment by Hari-Pi** [comment]
I just updated the file permissions, sorry forgot to do that
